config/routes.rb
Rails.application.routes.draw do
  get 'costume_tags/new'
  get 'costume_tags/create'
  get 'costume_tags/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :costumes do
    resources :bookings, only: [:new, :create]
  end
  get "/dashboard", to: "dashboards#dashboard", as: :dashboard

  resources :bookings, only: [] do
    member do
      post :accept
      post :reject
    end
  end

  resources :bookings, only: [] do
    resources :reviews,only: [:new, :create]
  end

   resources :costumes, only: [] do
    resources :costume_tags, only: [:new, :create]
  end

  resources :costume_tags, only: :destroy

end

app/models/costume.rb
class Costume < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  validates :name, :description, :price, :size, presence: true
  validates :price, :price, numericality: { only_integer: true }
  has_many :bookings
  has_many :reviews, through: :bookings
  has_many_attached :photos
  has_many :costume_tags, dependent: :destroy
  has_many :tags, through: :costume_tags
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?

  pg_search_scope :tag_search,
                  associated_against: {
                    tags: [:name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  def unavailable_dates
    bookings.where(status: "accepted").pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  def pretty_tags
    tags.pluck(:name).join(", ")
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :set_costume, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @costumes = Costume.all

    if params[:search].present?
      # raise
      @costumes = @costumes.where("city ILIKE ?", "%#{params[:search][:city]}%") if params[:search][:city].present?

      @costumes = @costumes.where(gender: params[:search][:gender]) if params[:search][:gender].present?

      @costumes = @costumes.where(size: params[:search][:size]) if params[:search][:size].present?
      # @costumes = @costumes.tag_search(params[:search][:tag]) if params[:search][:tag].present?
      @costumes = @costumes.joins(:tags).where(tags: { name: params[:search][:tag].map(&:capitalize) }).distinct if params[:search][:tag].present?
      # if params[:search][:tag].present?
      #   params[:search][:tag].each do |tag_id|
      #   # @tags = Tag.find(params[:search][:tag])
      #   # @tags.each do |tag|

      #  end
      # end

    end

    @markers = Costume.geocoded.map do |costume|
      {
        lat: costume.latitude,
        lng: costume.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { costume: costume })
      }
    end
  end

  def show
    authorize @costume
    @booking = Booking.new
    @reviews = @costume.reviews
  end

  def edit
    authorize @costume
  end

  def update
    authorize @costume
    if @costume.update(costume_params)
      redirect_to costume_path(@costume)
    else
      render :new
    end
  end

  def new
    @costume = Costume.new
    authorize @costume
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user = current_user
    authorize @costume
    if @costume.save
      params[:costume][:tags].each do |tag_id|
        CostumeTag.create(tag_id: tag_id, costume: @costume)
      end
      redirect_to costume_path(@costume)
    else
      render :new
    end
  end

  def destroy
    authorize @costume
    @costume.destroy
    redirect_to costumes_path
  end

  private

  def set_costume
    @costume = Costume.find(params[:id])
  end

  def costume_params
    params.require(:costume).permit(:name, :description, :price, :size, :gender, :city, :tag, photos: [])
  end
end

app/views/costumes/_form.html.erb
<%= simple_form_for(@costume) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :city %>
  <%= f.input :price %>
  <%= f.input :size, :collection => ["x-small", "small", "medium", "large", "x-large"] %>
  <%= f.input :gender, :collection => ["male", "female", "unisex"] %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.simple_fields_for :tag do |z| %>
  <%= f.input :tags, collection: Tag.all, input_html: { multiple: true, class: 'multiple-select' }, include_hidden: false %>
  <% end %>
  <%= f.submit "Upload Costume", class: "btn btn-primary" %>
<% end %>

app/views/costumes/_info_window.html.erb
<h2 style="color:#32E0C4;"><%= costume.city %></h2>

  <%= link_to "Show all the costumes in #{costume.city}", costumes_path(search: {city: costume.city} ) %>

app/views/costumes/edit.html.erb
<div class= "container py-5">
<h1 class= "row justify-content-center">Edit costume</h1>
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= simple_form_for  @costume  do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :city %>
        <%= f.input :price %>
        <%= f.input :size, :collection => ["x-small", "small", "medium", "large", "x-large"] %>
        <%= f.input :gender, :collection => ["male", "female", "unisex"] %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>


        <%= f.submit "Done!", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/costumes/index.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="col-md-8">
          <h2 class="my-4 text-center">Search Costumes:</h2>
          <form class="" action="/costumes">
            <div class="d-flex justify-content-between">
              <input class="form-control mr-sm-2 mb-3 w-60" type="text" name="search[city]" placeholder="Enter City" aria-label="Search">
              <div class="form-group w-100">
              <select id="tag-selector" class="form-control mr-sm-2 mb-3" name="search[tag][]" multiple>
                <% Tag.all.each do |tag| %>
                  <option><%= tag.name %></option>
                <% end %>
              </select>
            </div>
              <%= link_to costumes_path do %>
                <i class="fas fa-sync mt-2 ml-2"></i>
              <% end %>
            </div>
            <div class="d-flex align-items-center">
              <div class="check-box mr-5">
                <p>Gender</p>
                <% ["male", "female", "unisex"].each do |gender| %>
                <label for="<%= gender %>"><%= gender.capitalize %></label>
                <input hidden type="checkbox" value="<%= gender %>" id="<%= gender %>" name="search[gender]">
                <% end %>
              </div>
              <div class="check-box mr-5">
                <p>Size</p>
                <% ["x-small", "small", "medium", "large", "x-large"].each do |size| %>
                <label for="<%= size %>"><%= size %></label>
                <input hidden type="checkbox" value="<%= size %>" id="<%= size %>" name="search[size]">
                <% end %>
              </div>
              <button class="btn btn-outline-success px-4 my-2 my-sm-0 align-self-end" type="submit">Search</button>
            </div>
          </form>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col-md-8">
          <% @costumes.each do |costume| %>
          <% if costume.photos.attached? %>
          <div class="col-md-12">
            <div class="costume-card card m-4 p-3 flex-row">
              <div class="row w-100">
                <div class="col-md-4">
                  <%= cl_image_tag costume.photos.first.key %>
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title"><%= link_to costume.name, costume_path(costume)  %></h5>
                    <p class="card-text"><%= costume.description %></p>
                    <p class="card-text">$<%= costume.price %></p>
                    <% if policy(costume).edit? %>
                    <%= link_to "Edit", edit_costume_path(costume) %>
                    <% end %>
                    <% if policy(costume).destroy? %>
                    <%= link_to "Delete", costume_path(costume), method: :delete, data: { confirm: "Delete #{costume.name}?"} %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
        <div class="col-md-4">
          <div id="map"
          style="width: 100%; height: 100vh; top:60px"
          class= "position-fixed"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>

app/views/costumes/new.html.erb
<div class = "container py-5">
    <%= render "form" %>
</div>

app/views/costumes/show.html.erb
<div class = "container py-5">
<div class="d-flex">
  <div class="show-card-image">
    <% @costume.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </div>
    <div class="show-card-text pl-4">
  <h2><%= @costume.name %></h2>
    <p><%= @costume.description %></p>
    <p>City: <%= @costume.city %></p>
    <p>Price: <%= @costume.price %></p>
    <p>Size: <%= @costume.size %></p>
    <p>Gender: <%= @costume.gender %></p>
    <p>Tags: <%= @costume.pretty_tags %></p>
  </div>
  </div>
      <% if policy(Booking.new(costume: @costume)).create? %>
        <div class="text-dark shadow p-3 mb-5 mt-3 bg-white rounded" id='costume-booking-dates' data-unavailable="<%= @costume.unavailable_dates.to_json %>">
          <h2 class="text-center">Book <%= @costume.name.capitalize %></h2>
          <%= simple_form_for [@costume, @booking] do |f| %>
            <%= f.input :start_date, as: :string, input_html: {class: "datepicker"} %>
            <%= f.input :end_date, as: :string, input_html: {class: "datepicker"} %>
            <%= f.submit "Complete Booking", class: "btn btn-primary" %>
            <%= link_to "Back to Search", costumes_path(search: { city: params[:city], size: params[:size], gender: params[:gender], tag: params[:tag] }), class: "btn btn-primary" %>
          <% end %>
        </div>
      <% end %>
    <%= link_to "Back to Dashboard", dashboard_path %>


  <% @costume.reviews.each do |review| %>
    <div class="card text-dark">
      <p><%= review.title %></p>
      <p><%= review.description %></p>
      <p>Rating: <%= review.rating %></p>
    <% end %>
    </div>
</div>