config/routes.rb
Rails.application.routes.draw do
  get 'costume_tags/new'
  get 'costume_tags/create'
  get 'costume_tags/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :costumes do
    resources :bookings, only: [:new, :create]
  end
  get "/dashboard", to: "dashboards#dashboard", as: :dashboard

  resources :bookings, only: [] do
    member do
      post :accept
      post :reject
    end
  end

  resources :bookings, only: [] do
    resources :reviews,only: [:new, :create]
  end

   resources :costumes, only: [] do
    resources :costume_tags, only: [:new, :create]
  end

  resources :costume_tags, only: :destroy

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :costume
  belongs_to :user
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date
  has_one :review

  before_create :set_status

  def set_status
    self.status = "pending"
  end
  
  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:accept, :reject]

  def new
    @booking = Booking.new
    authorize @booking
  end

 # /costumes/:costume_id/bookings
  def create
   
    @booking = Booking.new(booking_params)
    
    @booking.user = current_user
    @costume = Costume.find(params[:costume_id])
    @booking.costume = @costume
    authorize @booking
    
    if @booking.save
      redirect_to dashboard_path
    else
      render "costumes/show"
    end
  end

  def accept
    authorize @booking
    @booking.status = "accepted"
    @booking.save
    redirect_to dashboard_path
  end

  def reject
    authorize @booking
    @booking.status = "rejected"
    @booking.save
    redirect_to dashboard_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end

end

app/views/bookings/_card.html.erb
<div class="card-product rounded">
  <% if booking.costume.photos.any? %>
    <%= cl_image_tag booking.costume.photos.first.key, height: 300, width: 400, crop: :fill %>
  <% end %>
  <div class="card-product-infos d-flex justify-content-between w-100 align-items-center">
    <div class="">
      <h2><%= booking.costume.name %></h2>
      <p><%= booking.start_date.strftime("%A, %b %d %Y") %> to <%= booking.end_date.strftime("%A, %b %d %Y") %></p>
      <p><%= booking.status %></p>
    </div>
    <div class="card-buttons">
    <% if booking.status == "pending" && owner %>
      <%= link_to "ACCEPT", accept_booking_path(booking), method: :post, class: "btn btn-primary mr-2" %>
      <%= link_to "REJECT", reject_booking_path(booking), method: :post, class: "btn btn-danger mr-3" %>
    <% end %>
    <% if booking.end_date < Date.today && !owner && booking.status == "accepted" %>
      <%= link_to "Leave a review", new_booking_review_path(booking), class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>