config/routes.rb
Rails.application.routes.draw do
  get 'costume_tags/new'
  get 'costume_tags/create'
  get 'costume_tags/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :costumes do
    resources :bookings, only: [:new, :create]
  end
  get "/dashboard", to: "dashboards#dashboard", as: :dashboard

  resources :bookings, only: [] do
    member do
      post :accept
      post :reject
    end
  end

  resources :bookings, only: [] do
    resources :reviews,only: [:new, :create]
  end

   resources :costumes, only: [] do
    resources :costume_tags, only: [:new, :create]
  end

  resources :costume_tags, only: :destroy

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex p-3 justify-content-center" style="flex-direction: column; align-items: center;">
  <div class="footer-links justify-content-center">
    <a href="#"><i class="fab fa-github justify-content-center"></i></a>
    <a href="#"><i class="fab fa-instagram justify-content-center"></i></a>
    <a href="#"><i class="fab fa-facebook justify-content-center"></i></a>
    <a href="#"><i class="fab fa-twitter justify-content-center"></i></a>
    <a href="#"><i class="fab fa-linkedin justify-content-center"></i></a>
    <p></p>
    </div>
    <div class="footer-copyright">
      This footer is made with <i class="fas fa-heart" id = ></i> at Le Wagon
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= cl_image_tag("https://res.cloudinary.com/dobjv8usn/image/upload/v1606804987/Confetti/LogoWhite_l5fn0t.png") %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <p  class="mb-0 nav-link dropdown-toggle" id="navbarDropdown" data-toggle= "dropdown"  aria-haspopup="true", aria-expanded="false"><%= current_user.email %></p>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %></strong>
            <%= link_to "Help", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></strong>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "View all costumes", costumes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <strong id><%= link_to "Login", new_user_session_path, class: "nav-link login-button" %></strong>
        </li>
      <% end %>
    </ul>
  </div>

</div>