config/routes.rb
Rails.application.routes.draw do
  get 'costume_tags/new'
  get 'costume_tags/create'
  get 'costume_tags/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :costumes do
    resources :bookings, only: [:new, :create]
  end
  get "/dashboard", to: "dashboards#dashboard", as: :dashboard

  resources :bookings, only: [] do
    member do
      post :accept
      post :reject
    end
  end

  resources :bookings, only: [] do
    resources :reviews,only: [:new, :create]
  end

   resources :costumes, only: [] do
    resources :costume_tags, only: [:new, :create]
  end

  resources :costume_tags, only: :destroy

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized, only: [:dashboard]
  def dashboard
    @renter_pending_bookings = current_user.bookings.where(status: "pending")
    @renter_accepted_bookings = current_user.bookings.where(status: "accepted")
    @renter_rejected_bookings = current_user.bookings.where(status: "rejected")
    @owner_bookings = Booking.joins(:costume).where(costumes: {user_id: current_user.id})
    @owner_completed_bookings = @owner_bookings.where(status: "accepted").where("end_date < ?", Date.today)
    @renter_completed_bookings = current_user.bookings.where(status: "accepted").where("end_date < ?", Date.today)
  end
end

app/views/dashboards/dashboard.html.erb
<div class="container py-5">

  <h2 class="text-center mt-1 mb-3">Pending Bookings</h2>
  <% @owner_bookings.each do |booking| %>
    <% if booking.status == "pending" %>
      <%= render 'bookings/card', booking: booking, owner: true %>
    <% end %>
  <% end %>
  <% @renter_pending_bookings.each do |booking| %>
    <%= render 'bookings/card', booking: booking, owner: false%>
  <% end %>

  <h2 class="text-center mt-1 mb-3">Upcoming Bookings</h2>
  <% @owner_bookings.each do |booking| %>
    <% if booking.status == "accepted" && booking.end_date > Date.today %>
      <%= render 'bookings/card', booking: booking, owner: true %>
    <% end %>
  <% end %>
  <% @renter_accepted_bookings.each do |booking| %>
    <%= render 'bookings/card', booking: booking, owner: false%>
  <% end %>

  <h2 class="text-center mt-1 mb-3">Completed Bookings of Your Costumes</h2>
    <% @owner_completed_bookings.each do |booking| %>
    <%= render 'bookings/card', booking: booking, owner: true %>
  <% end %>
   <h2 class="text-center mt-1 mb-3">Leave a Review</h2>
  <% @renter_completed_bookings.each do |booking| %>
    <%= render 'bookings/card', booking: booking, owner: false %>
  <% end %>

  <h2 class="text-center mt-1 mb-3"><%= link_to "List new costume", new_costume_path %></h2>
  <h2 class="text-center mt-1 mb-3"><%= link_to "View all costumes", costumes_path %></h2>